language: c

sudo: required

services:
    - docker

before_install:
    - docker pull amigadev/crosstools:ppc-morphos
    - docker pull amigadev/crosstools:ppc-amigaos

addons:
    apt:
        update: true

git:
    depth: 1

script:
    - wget -nc -q http://aminet.net/dev/mui/MCC_TheBar-26.21.lha -O thebar.lha
    - wget -nc -q http://hpux.connect.org.uk/ftp/hpux/Misc/lha-114i/lha-114i-src-11.11.tar.gz -O lha.tar.gz
    - wget -nc -q https://muidev.de/download/MUI%205.0%20-%20Release/MUI-5.0-2019R2-os4.lha
    - wget -nc -q 'http://hyperion-entertainment.biz/index.php/downloads?view=download&amp;format=raw&amp;file=69' -O SDK_53.24.lha
    - tar xfz lha.tar.gz
    - make -C lha-114i
    - cp lha-114i/src/lha dist
    - dist/lha efq thebar.lha
    - dist/lha efq MUI-5.0-2019R2-os4.lha
    - dist/lha efq SDK_53.24.lha
    - dist/lha efq SDK_Install/clib2-1.205.lha
    - docker run --rm -v ${PWD}:/work -it amigadev/crosstools:ppc-morphos bash -c 'cp -r MCC_TheBar/Developer/C/include/* /opt/ppc-morphos/os-include/ && make dist CC=ppc-morphos-gcc LHA=/work/dist/lha ARC=ppc UNM=MorphOS'
    - mkdir artefacts
    - cp dist/tmp/* artefacts
    - sudo make clean CC=ppc-morphos-gcc LHA=dist/lha ARC=ppc UNM=MorphOS
    - docker run --rm -v ${PWD}:/work -it amigadev/crosstools:ppc-morphos bash -c 'cp /opt/ppc-morphos/os-include/devices/rawkeycodes.h .'
    - docker run --rm -v ${PWD}:/work -it amigadev/crosstools:ppc-amigaos bash -c 'cp -r MCC_TheBar/Developer/C/include/* /opt/ppc-amigaos/ppc-amigaos/SDK/include/include_h && cp rawkeycodes.h /opt/ppc-amigaos/ppc-amigaos/SDK/include/include_h/devices && cp -r SDK/MUI/C/include/* /opt/ppc-amigaos/ppc-amigaos/SDK/include/include_h && cp clib2/lib/libauto.a /opt/ppc-amigaos/ppc-amigaos/SDK/clib2/lib && make dist CC=ppc-amigaos-gcc LHA=/work/dist/lha ARC=ppc UNM=AmigaOS'
    - cp dist/tmp/* artefacts

deploy:
    provider: releases
    api_key: '$GITHUB_API_KEY'
    file_glob: true
    file: "artefacts/*"
    skip_cleanup: true
    on:
        tags: true
